server:
  port: ${PORT:8889}

spring:
  zipkin:
    baseUrl: http://localhost:9411  

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

message: Consumer configuration server is alive 2!

